---
- hosts: hubs
  vars:
    nvm_version: v0.33.11
    node_version: v8.11.3
  roles:
  - base
  - node
  - app

- hosts: display-hubs
  vars:
    nvm_version: v0.33.11
    node_version: v8.11.3
  roles:
  - display

- hosts: cloud-servers
  vars:
    local_wifi_page_path: ./www-wifi-page
  roles:
  - www-wifi-page
