---
- hosts: wifis
  tasks:
    - name: get wpa_supplicant
      fetch:
        src: /etc/wpa_supplicant/wpa_supplicant.conf
        dest: wpa_supplicants
    - name: get wpa_supplicant wlan0
      fetch:
        src: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
        dest: wpa_supplicants
    - name: get wpa_supplicant wlan1
      fetch:
        src: /etc/wpa_supplicant/wpa_supplicant-wlan1.conf
        dest: wpa_supplicants
