---
- hosts: wifis
  vars:
    user: pi
  tasks:
  - name: install apt packages
    become: true
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
      - hostapd
      - dnsmasq

  - name: configure dhcpcd
    become: yes
    lineinfile:
      path: /etc/default/hostapd
      regexp: '^DAEMON_CONF=""$'
      line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
      state: present
      create: yes
    # TODO make this a template with SSID and password
  - name: hostapd config
    become: yes
    template:
      src: ./hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
      owner: root
      group: netdev
      mode: 0664
  - name: restart hostapd
    become: yes
    systemd:
      name: hostapd
      enabled: yes
      state: restarted
      daemon_reload: yes
  - name: dnsmasq config
    become: yes
    copy:
      src: ./dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
  - name: restart dnsmasq
    become: yes
    systemd:
      name: dnsmasq
      enabled: yes
      state: restarted
      daemon_reload: yes
  - name: dhcpcd config
    become: yes
    copy:
      src: ./dhcpcd.conf
      dest: /etc/dhcpcd.conf
      owner: root
      group: netdev
      mode: 0664

  - name: iptables config
    become: yes
    copy:
      src: ./iptables.ipv4.nat
      dest: /etc/iptables.ipv4.nat
      owner: root
      group: root
      mode: 0644
  - name: configure iptables-restore
    become: yes
    lineinfile:
      path: /home/{{ user }}/.profile
      insertbefore: '^exit 0$'
      line: 'iptables-restore < /etc/iptables.ipv4.nat'
      state: present
      create: yes
