---
- hosts: hubs
  vars:
    user: pi
    cron_email: johnelliott703@gmail.com
  tasks:
  - name: install apt packages
    become: true
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
      - build-essential
      - libssl-dev
      - avahi-daemon
      - hostapd
      - dnsmasq
      - vim
      - tmux
      - ssmtp
      - mpack
      - rsync
  - name: download .vimrc
    get_url:
      url: https://raw.githubusercontent.com/johnelliott/dotfiles/master/.vimrc.min
      dest: ~/.vimrc
  - name: cron email
    cronvar:
      name: EMAIL
      value: "{{ cron_email }}"
  - name: wpa_supplicant
    become: yes
    copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf
    # TODO restart wpa supplicant and services e.g. wpa_cli -i wlan0 reconfigure
    # notify: reload-wifi

    # TODO make this a template with SSID and password
  - name: hostapd config
    become: yes
    template:
      src: ./hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
      owner: root
      group: netdev
      mode: 0664
  - name: restart hostapd
    become: yes
    systemd:
      name: hostapd
      enabled: yes
      state: restarted
      daemon_reload: yes
  - name: dnsmasq config
    become: yes
    copy:
      src: ./dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
  - name: restart dnsmasq
    become: yes
    systemd:
      name: dnsmasq
      enabled: yes
      state: restarted
      daemon_reload: yes
  - name: dhcpcd config
    become: yes
    copy:
      src: ./dhcpcd.conf
      dest: /etc/dhcpcd.conf
      owner: root
      group: netdev
      mode: 0664

  - name: iptables config
    become: yes
    copy:
      src: ./iptables.ipv4.nat
      dest: /etc/iptables.ipv4.nat
      owner: root
      group: root
      mode: 0644
  - name: configure iptables-restore
    become: yes
    lineinfile:
      dest: /home/{{ user }}/.profile
      insertbefore: '^exit 0$'
      line: 'iptables-restore < /etc/iptables.ipv4.nat'
      create: yes

  handlers:
  - name: reload-wifi
    become: yes
    shell: wpa_cli -i wlan0 reconfigure
  # Is this a bad idea? Will I lose ssh connection for ansible?
  - name: restart networking
    become: yes
    service:
      name: networking
      state: restarted
